version: '{build}-{branch}'
image: Visual Studio 2019
shallow_clone: true

environment:
  matrix:

    - CONFIG: Release
      ARCH: amd64
      GENERATOR: Ninja

    - CONFIG: Debug
      ARCH: amd64
      GENERATOR: MSVS

    - CONFIG: RelWithDebInfo
      ARCH: x86
      GENERATOR: MSVS

    - CONFIG: Debug
      ARCH: x86
      GENERATOR: Ninja

cache:
  - .build\_PrimalDownloads
  - .build-import\_PrimalDownloads

install:
  - if "%GENERATOR%"=="MSVS" (set CMAKE_GENERATOR=Visual Studio 16 2019) else (set CMAKE_GENERATOR=%GENERATOR%)
  - if "%GENERATOR%"=="Ninja" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - if "%GENERATOR%"=="Ninja" cinst ninja
  - if "%GENERATOR%"=="Ninja" set EXTRA_CMAKE_FLAGS=-DCMAKE_BUILD_TYPE=%CONFIG%
  - if "%GENERATOR%"=="MSVS" if "%ARCH%"=="amd64" (set CMAKE_GENERATOR_PLATFORM=x64) else (set CMAKE_GENERATOR_PLATFORM=Win32)
  - if "%GENERATOR%"=="MSVS" set EXTRA_BUILD_FLAGS=--config %CONFIG% -- /nologo "/verbosity:minimal"
  - if "%GENERATOR%"=="MSVS" set EXTRA_TEST_FLAGS=--build-config %CONFIG%

build_script:
  - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\.build
  - set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\.install
  - cmake -S "%APPVEYOR_BUILD_FOLDER%" -B "%BUILD_DIR%" %EXTRA_CMAKE_FLAGS% -DCMAKE_INSTALL_PREFIX="%INSTALL_DIR%" -DPRIMAL_TESTS=ON
  - cmake --build "%BUILD_DIR%" %EXTRA_BUILD_FLAGS%
  - cmake --build "%BUILD_DIR%" --target install %EXTRA_BUILD_FLAGS%
  - set IMPORT_DIR=%APPVEYOR_BUILD_FOLDER%\.build-import
  - cmake -S "%APPVEYOR_BUILD_FOLDER%\tests\import" -B "%IMPORT_DIR%" %EXTRA_CMAKE_FLAGS% -DCMAKE_PREFIX_PATH="%INSTALL_DIR%"
  - cmake --build "%IMPORT_DIR%" %EXTRA_BUILD_FLAGS%

test_script:
  - cd %BUILD_DIR%
  - ctest --verbose %EXTRA_TEST_FLAGS%
